### Introduction to pandas!

What we will learn in this notebook:
- how to open and read in a csv spreadsheet
- how to look at the data we have
- how to select columns
- how to do some math with them

First we need to import pandas as a library. We import the library and then tell Python to refer to it as `pd`:

In [1]:
import pandas as pd

### Reading spreadsheets

This is how you read a spreadsheet and assign it to a variable:

In [2]:
census_data = pd.read_csv('../data/2016_census_data.csv')

### Looking at your data

To look at the data you just read into Python, you can just run a cell with the name of the variable:

In [3]:
census_data

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365
5,34003003200,Census Tract 32,Bergen County,New Jersey,5044,69531,322400,1417,1342,186,19,1882,0,6,64,1564
6,34003003300,Census Tract 33,Bergen County,New Jersey,6638,97957,328100,1737,2437,400,0,2131,0,0,148,1522
7,34003003401,Census Tract 34.01,Bergen County,New Jersey,2958,122650,385200,941,1704,109,0,520,0,0,36,589
8,34003003402,Census Tract 34.02,Bergen County,New Jersey,3827,105776,356100,1237,1937,260,0,733,0,4,122,771
9,34003003500,Census Tract 35,Bergen County,New Jersey,4100,52382,340200,891,886,502,16,1160,0,0,59,1493
10,34003004001,Census Tract 40.01,Bergen County,New Jersey,3372,76979,331300,537,1635,145,0,169,0,42,80,1301
11,34003004002,Census Tract 40.02,Bergen County,New Jersey,4976,78306,299700,1228,1694,462,0,561,0,20,29,2210
12,34003005000,Census Tract 50,Bergen County,New Jersey,6238,84268,386200,1725,4095,0,9,444,0,23,103,1564
13,34003006100,Census Tract 61,Bergen County,New Jersey,7159,63071,416900,2215,4288,124,0,728,0,71,121,1827
14,34003006201,Census Tract 62.01,Bergen County,New Jersey,4416,49883,429500,1288,2307,68,0,602,0,70,74,1295
15,34003006202,Census Tract 62.02,Bergen County,New Jersey,5073,81273,405900,2501,2795,145,0,1398,14,15,106,600
16,34003006300,Census Tract 63,Bergen County,New Jersey,8013,54788,412300,2105,3108,297,0,589,0,21,320,3678
17,34003007001,Census Tract 70.01,Bergen County,New Jersey,3899,100250,514100,1560,2146,28,8,1355,0,0,0,362
18,34003007002,Census Tract 70.02,Bergen County,New Jersey,4751,143780,745300,1979,2482,86,0,2068,0,16,27,72
19,34003008000,Census Tract 80,Bergen County,New Jersey,8745,117164,540700,3686,5641,64,14,2150,0,0,105,785
20,34003009100,Census Tract 91,Bergen County,New Jersey,5007,150139,652800,2083,2961,11,0,1476,0,0,37,522
21,34003009200,Census Tract 92,Bergen County,New Jersey,3446,168371,644700,1609,2728,36,6,547,0,0,59,76
22,34003010100,Census Tract 101,Bergen County,New Jersey,5864,98987,364200,1832,3953,95,0,900,0,0,100,816
23,34003010200,Census Tract 102,Bergen County,New Jersey,4275,75550,348600,1049,2514,146,26,716,0,0,85,805
24,34003010300,Census Tract 103,Bergen County,New Jersey,7649,106750,356700,2508,4640,271,0,1152,0,0,64,1522
25,34003011100,Census Tract 111,Bergen County,New Jersey,4293,68442,326100,836,1969,208,8,401,0,42,145,1528
26,34003011200,Census Tract 112,Bergen County,New Jersey,5077,69310,353400,900,2303,471,0,418,0,33,127,1725
27,34003011300,Census Tract 113,Bergen County,New Jersey,4240,88045,343300,1041,2447,150,52,325,0,0,183,1083
28,34003011400,Census Tract 114,Bergen County,New Jersey,6525,76709,375100,1490,4140,274,0,426,34,0,0,1651
29,34003012001,Census Tract 120.01,Bergen County,New Jersey,5933,70769,410500,1978,2885,282,0,896,0,0,46,1824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4670,36119014811,Census Tract 148.11,Westchester County,New York,5773,134773,445700,1888,4553,206,0,201,0,41,36,736
4671,36119014901,Census Tract 149.01,Westchester County,New York,6524,134797,638700,2367,5634,18,33,236,0,0,46,557
4672,36119014903,Census Tract 149.03,Westchester County,New York,4526,87746,443400,2104,4265,17,35,3,0,0,0,206
4673,36119014907,Census Tract 149.07,Westchester County,New York,4255,110610,395500,1241,3452,151,17,185,0,0,1,449
4674,36119014908,Census Tract 149.08,Westchester County,New York,2918,138571,614400,1034,2572,2,0,148,0,0,30,166
4675,36119014909,Census Tract 149.09,Westchester County,New York,2907,104286,432600,1528,2577,0,0,148,0,0,0,182
4676,36119015000,Census Tract 150,Westchester County,New York,5178,126724,584300,2239,4366,103,28,82,0,27,201,377
4677,36119981000,Census Tract 9810,Westchester County,New York,1921,57353,-666666666,381,676,549,0,353,0,9,4,330
4678,36119982000,Census Tract 9820,Westchester County,New York,1562,-666666666,-666666666,46,175,809,0,68,0,0,14,496
4679,36119983000,Census Tract 9830,Westchester County,New York,1331,-666666666,-666666666,112,554,465,46,6,0,0,84,176
4680,36119984000,Census Tract 9840,Westchester County,New York,288,38929,-666666666,52,149,97,0,0,0,0,4,38
4681,36119985000,Census Tract 9850,Westchester County,New York,2485,-666666666,-666666666,15,1567,324,13,104,10,0,59,417
4682,42103950102,Census Tract 9501.02,Pike County,Pennsylvania,2383,57292,188200,467,2077,7,0,24,0,15,6,254
4683,42103950103,Census Tract 9501.03,Pike County,Pennsylvania,2336,55833,174600,450,2013,10,15,19,6,22,122,129
4684,42103950104,Census Tract 9501.04,Pike County,Pennsylvania,2311,53789,215500,407,2128,14,9,27,0,0,15,127
4685,42103950201,Census Tract 9502.01,Pike County,Pennsylvania,3470,69554,225200,722,2665,362,0,0,0,34,56,353
4686,42103950202,Census Tract 9502.02,Pike County,Pennsylvania,1562,51016,180700,223,1330,107,0,0,0,0,69,56
4687,42103950301,Census Tract 9503.01,Pike County,Pennsylvania,2494,50129,182400,640,2381,28,0,0,0,0,58,27
4688,42103950302,Census Tract 9503.02,Pike County,Pennsylvania,771,61875,336500,265,745,0,8,18,0,0,0,0
4689,42103950501,Census Tract 9505.01,Pike County,Pennsylvania,1578,52470,197400,171,1197,81,0,6,0,12,61,221
4690,42103950502,Census Tract 9505.02,Pike County,Pennsylvania,3132,57875,205300,728,2186,237,0,120,0,31,75,483
4691,42103950601,Census Tract 9506.01,Pike County,Pennsylvania,1560,68319,269200,354,1404,33,0,11,0,0,53,59
4692,42103950603,Census Tract 9506.03,Pike County,Pennsylvania,1093,56250,281400,255,1009,16,0,0,0,0,16,52
4693,42103950605,Census Tract 9506.05,Pike County,Pennsylvania,6056,83220,207100,1048,5487,333,21,0,9,11,0,195
4694,42103950606,Census Tract 9506.06,Pike County,Pennsylvania,5647,86250,237300,1369,4951,71,0,156,0,12,20,437
4695,42103950701,Census Tract 9507.01,Pike County,Pennsylvania,4107,61726,155800,537,3665,12,0,67,0,0,26,337
4696,42103950702,Census Tract 9507.02,Pike County,Pennsylvania,3119,59239,151100,405,2908,44,0,60,0,0,19,88
4697,42103950801,Census Tract 9508.01,Pike County,Pennsylvania,4403,55530,120000,718,2777,705,0,53,0,0,97,771
4698,42103950802,Census Tract 9508.02,Pike County,Pennsylvania,6004,50724,146700,795,3072,970,20,44,0,0,11,1887
4699,42103950900,Census Tract 9509,Pike County,Pennsylvania,4184,49453,146100,721,3888,55,29,22,0,0,9,181

Oops, that's a little long. Maybe we just want to see the first 10 rows:

In [4]:
census_data.head(10)

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365
5,34003003200,Census Tract 32,Bergen County,New Jersey,5044,69531,322400,1417,1342,186,19,1882,0,6,64,1564
6,34003003300,Census Tract 33,Bergen County,New Jersey,6638,97957,328100,1737,2437,400,0,2131,0,0,148,1522
7,34003003401,Census Tract 34.01,Bergen County,New Jersey,2958,122650,385200,941,1704,109,0,520,0,0,36,589
8,34003003402,Census Tract 34.02,Bergen County,New Jersey,3827,105776,356100,1237,1937,260,0,733,0,4,122,771
9,34003003500,Census Tract 35,Bergen County,New Jersey,4100,52382,340200,891,886,502,16,1160,0,0,59,1493

Or the last four:

In [5]:
census_data.tail(4)

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
4696,42103950702,Census Tract 9507.02,Pike County,Pennsylvania,3119,59239,151100,405,2908,44,0,60,0,0,19,88
4697,42103950801,Census Tract 9508.01,Pike County,Pennsylvania,4403,55530,120000,718,2777,705,0,53,0,0,97,771
4698,42103950802,Census Tract 9508.02,Pike County,Pennsylvania,6004,50724,146700,795,3072,970,20,44,0,0,11,1887
4699,42103950900,Census Tract 9509,Pike County,Pennsylvania,4184,49453,146100,721,3888,55,29,22,0,0,9,181

or we want to know the length of the entire set:

In [6]:
len(census_data)

4700

In [7]:
census_data.T

,0,1,2,3,4,5,6,7,8,9,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
geoid,34003001000,34003002100,34003002200,34003002300,34003003100,34003003200,34003003300,34003003401,34003003402,34003003500,...,42103950502,42103950601,42103950603,42103950605,42103950606,42103950701,42103950702,42103950801,42103950802,42103950900
name,Census Tract 10,Census Tract 21,Census Tract 22,Census Tract 23,Census Tract 31,Census Tract 32,Census Tract 33,Census Tract 34.01,Census Tract 34.02,Census Tract 35,...,Census Tract 9505.02,Census Tract 9506.01,Census Tract 9506.03,Census Tract 9506.05,Census Tract 9506.06,Census Tract 9507.01,Census Tract 9507.02,Census Tract 9508.01,Census Tract 9508.02,Census Tract 9509
county,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,Bergen County,...,Pike County,Pike County,Pike County,Pike County,Pike County,Pike County,Pike County,Pike County,Pike County,Pike County
state,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,New Jersey,...,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania,Pennsylvania
total_population,6767,1522,5389,5828,4946,5044,6638,2958,3827,4100,...,3132,1560,1093,6056,5647,4107,3119,4403,6004,4184
median_income,151641,114545,90647,112031,76906,69531,97957,122650,105776,52382,...,57875,68319,56250,83220,86250,61726,59239,55530,50724,49453
median_home_value,680000,2000001,453800,610000,301900,322400,328100,385200,356100,340200,...,205300,269200,281400,207100,237300,155800,151100,120000,146700,146100
educational_attainment,3045,836,1791,2363,1588,1417,1737,941,1237,891,...,728,354,255,1048,1369,537,405,718,795,721
white_alone,5667,788,3481,3595,1803,1342,2437,1704,1937,886,...,2186,1404,1009,5487,4951,3665,2908,2777,3072,3888
black_alone,75,141,99,89,306,186,400,109,260,502,...,237,33,16,333,71,12,44,705,970,55
native,0,0,9,37,0,19,0,0,0,16,...,0,0,0,21,0,0,0,0,20,29
asian,759,444,1247,1627,1435,1882,2131,520,733,1160,...,120,11,0,0,156,67,60,53,44,22
native_hawaiian_pacific_islander,0,0,0,0,0,0,0,0,0,0,...,0,0,0,9,0,0,0,0,0,0
some_other_race_alone,0,0,36,0,13,6,0,0,4,0,...,31,0,0,11,12,0,0,0,0,0
two_or_more,132,27,19,32,24,64,148,36,122,59,...,75,53,16,0,20,26,19,97,11,9
hispanic_or_latino,134,122,504,448,1365,1564,1522,589,771,1493,...,483,59,52,195,437,337,88,771,1887,181

### Filtering by columns

How about filtering your data by columns? This is how you can do that:

In [8]:
census_data['black_alone']

0        75
1       141
2        99
3        89
4       306
5       186
6       400
7       109
8       260
9       502
10      145
11      462
12        0
13      124
14       68
15      145
16      297
17       28
18       86
19       64
20       11
21       36
22       95
23      146
24      271
25      208
26      471
27      150
28      274
29      282
       ...
4670    206
4671     18
4672     17
4673    151
4674      2
4675      0
4676    103
4677    549
4678    809
4679    465
4680     97
4681    324
4682      7
4683     10
4684     14
4685    362
4686    107
4687     28
4688      0
4689     81
4690    237
4691     33
4692     16
4693    333
4694     71
4695     12
4696     44
4697    705
4698    970
4699     55
Name: black_alone, Length: 4700, dtype: int64

You can also select multiple columns:

In [9]:
column_names  = ['black_alone', 'native']
census_data[column_names]

      black_alone  native
0              75       0
1             141       0
2              99       9
3              89      37
4             306       0
5             186      19
6             400       0
7             109       0
8             260       0
9             502      16
10            145       0
11            462       0
12              0       9
13            124       0
14             68       0
15            145       0
16            297       0
17             28       8
18             86       0
19             64      14
20             11       0
21             36       6
22             95       0
23            146      26
24            271       0
25            208       8
26            471       0
27            150      52
28            274       0
29            282       0
...           ...     ...
4670          206       0
4671           18      33
4672           17      35
4673          151      17
4674            2       0
4675            0       0
4676          103      28
4677          549       0
4678          809       0
4679          465      46
4680           97       0
4681          324      13
4682            7       0
4683           10      15
4684           14       9
4685          362       0
4686          107       0
4687           28       0
4688            0       8
4689           81       0
4690          237       0
4691           33       0
4692           16       0
4693          333      21
4694           71       0
4695           12       0
4696           44       0
4697          705       0
4698          970      20
4699           55      29

[4700 rows x 2 columns]

### Doing math with your data
There are a few nifty functions you can apply to your data columns.

In [10]:
census_data['black_alone'].sum()

3155672

In [11]:
census_data['black_alone'].median()

198.5

In [12]:
census_data['black_alone'].mean()

671.4195744680851

There is also this nifty function which gives you a quick overview of your data:

In [13]:
census_data['black_alone'].describe()

count     4700.000000
mean       671.419574
std       1041.216791
min          0.000000
25%         47.000000
50%        198.500000
75%        889.500000
max      17123.000000
Name: black_alone, dtype: float64

### Making new data columns
You can make a new column based on two columns like so:

In [14]:
census_data['black_alone_percentage'] = census_data['black_alone']/census_data['total_population']

In [15]:
census_data.head()

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134,0.011083
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122,0.092641
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504,0.018371
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448,0.015271
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365,0.061868

To overwrite your previous data you can just re-assign the column new values, the way you do with any variable:

In [16]:
census_data['black_alone_percentage'] = (census_data['black_alone']/census_data['total_population'])*100

In [17]:
census_data.head()

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134,1.108320
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122,9.264126
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504,1.837076
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448,1.527111
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365,6.186818

A quick sorting function can now help you find the spots with the highest or lowest black populations (we can go over this again next week):

In [18]:
census_data.sort_values(by='median_income', ascending = True)

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,black_alone_percentage
3712,36081062400,Census Tract 624,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3952,36081156700,Census Tract 1567,Queens County,New York,1382,-666666666,663500,218,324,255,0,500,0,0,10,293,18.451520
1546,36005017100,Census Tract 171,Bronx County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
2533,36047096000,Census Tract 960,Kings County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3928,36081138502,Census Tract 1385.02,Queens County,New York,37,-666666666,-666666666,17,16,4,0,0,0,0,0,17,10.810811
1540,36005016300,Census Tract 163,Bronx County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
2601,36047118000,Census Tract 1180,Kings County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3905,36081121100,Census Tract 1211,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3513,36081029900,Census Tract 299,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
1506,36005011000,Census Tract 110,Bronx County,New York,151,-666666666,-666666666,37,0,0,0,0,0,0,0,151,0.000000
801,34025804700,Census Tract 8047,Monmouth County,New Jersey,7,-666666666,-666666666,1,5,0,0,0,0,0,1,1,0.000000
2621,36047990100,Census Tract 9901,Kings County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3326,36081005000,Census Tract 50,Queens County,New York,62,-666666666,-666666666,22,18,0,4,0,0,0,0,44,0.000000
3316,36081003700,Census Tract 37,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3960,36081990100,Census Tract 9901,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
4542,36119005600,Census Tract 56,Westchester County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3190,36061031100,Census Tract 311,New York County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3185,36061029700,Census Tract 297,New York County,New York,18,-666666666,-666666666,0,0,18,0,0,0,0,0,0,100.000000
3872,36081107202,Census Tract 1072.02,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
1458,36005003700,Census Tract 37,Bronx County,New York,279,-666666666,-666666666,12,56,60,0,0,0,0,0,163,21.505376
1450,36005002400,Census Tract 24,Bronx County,New York,123,-666666666,-666666666,65,58,65,0,0,0,0,0,0,52.845528
3155,36061024000,Census Tract 240,New York County,New York,1742,-666666666,-666666666,103,386,883,14,51,31,10,11,356,50.688863
3858,36081099900,Census Tract 999,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
1443,36005000100,Census Tract 1,Bronx County,New York,7503,-666666666,-666666666,76,510,4496,14,135,0,34,74,2240,59.922698
3524,36081033100,Census Tract 331,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3548,36081038301,Census Tract 383.01,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3549,36081038302,Census Tract 383.02,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3827,36081091800,Census Tract 918,Queens County,New York,7,-666666666,-666666666,7,7,0,0,0,0,0,0,0,0.000000
3826,36081091602,Census Tract 916.02,Queens County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
3193,36061031900,Census Tract 319,New York County,New York,0,-666666666,-666666666,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845,36059518201,Census Tract 5182.01,Nassau County,New York,4319,207250,1518100,2142,3677,64,0,337,0,10,20,211,1.481824
2939,36061003300,Census Tract 33,New York County,New York,5030,207460,2000001,3196,3716,144,0,521,0,0,275,374,2.862823
4627,36119012303,Census Tract 123.03,Westchester County,New York,4815,207656,928600,2415,4136,35,0,258,0,0,28,358,0.726895
2973,36061006900,Census Tract 69,New York County,New York,2442,209167,1168600,1631,1900,49,0,237,0,20,74,162,2.006552
1873,36047002100,Census Tract 21,Kings County,New York,4628,211071,1368600,2918,3410,151,0,389,0,0,357,321,3.262748
2771,36059412600,Census Tract 4126,Nassau County,New York,3807,215313,891000,1823,3488,1,0,102,0,43,0,173,0.026267
536,34017018302,Census Tract 183.02,Hudson County,New Jersey,3726,216300,836800,2835,2737,41,0,554,0,0,103,291,1.100376
4597,36119010100,Census Tract 101,Westchester County,New York,4754,217273,903800,2619,3651,81,0,731,0,0,171,120,1.703828
2837,36059517701,Census Tract 5177.01,Nassau County,New York,8099,218125,1590400,3937,5840,163,0,1678,0,12,119,287,2.012594
535,34017018301,Census Tract 183.01,Hudson County,New Jersey,2375,218173,1078700,1720,1816,0,0,330,0,0,54,175,0.000000
4641,36119013201,Census Tract 132.01,Westchester County,New York,4316,220855,810800,2126,3331,127,0,374,8,18,79,379,2.942539
2638,36059301700,Census Tract 3017,Nassau County,New York,2719,222083,1420000,1424,2414,0,0,190,0,0,47,68,0.000000
4136,36103110101,Census Tract 1101.01,Suffolk County,New York,3696,223036,1373400,1783,3332,10,0,165,0,0,49,140,0.270563
1404,34039036500,Census Tract 365,Union County,New Jersey,5417,225074,877700,2819,4542,44,0,351,0,55,94,331,0.812258
2838,36059517705,Census Tract 5177.05,Nassau County,New York,2793,229318,1918600,1382,2185,50,0,429,0,0,9,120,1.790190
4628,36119012304,Census Tract 123.04,Westchester County,New York,4813,230357,1121500,2564,4330,45,0,185,0,8,96,149,0.934968
3071,36061016001,Census Tract 160.01,New York County,New York,3918,233529,2000001,2662,3215,12,0,307,0,0,115,269,0.306279
3047,36061014200,Census Tract 142,New York County,New York,4186,235083,2000001,2762,3877,11,0,130,0,32,68,68,0.262781
4640,36119013104,Census Tract 131.04,Westchester County,New York,6066,237500,947400,3170,5214,98,47,439,0,0,34,234,1.615562
4578,36119008500,Census Tract 85,Westchester County,New York,3258,241250,2000001,1715,2868,5,0,191,0,0,0,194,0.153468
320,34013016200,Census Tract 162,Essex County,New Jersey,3387,244375,707100,2029,2867,150,0,114,0,14,79,163,4.428698
4596,36119010000,Census Tract 100,Westchester County,New York,5387,250001,1438000,2956,4216,44,0,864,0,12,157,94,0.816781
4540,36119005400,Census Tract 54,Westchester County,New York,1593,250001,988300,839,1256,35,0,36,0,0,78,188,2.197112
4595,36119009900,Census Tract 99,Westchester County,New York,3008,250001,2000001,1629,2305,3,0,327,0,0,67,306,0.099734
358,34013020000,Census Tract 200,Essex County,New Jersey,5826,250001,1534600,3182,4334,28,0,1099,0,9,128,228,0.480604
4532,36119004700,Census Tract 47,Westchester County,New York,3596,250001,2000001,1649,3234,51,0,132,0,0,52,127,1.418242
141,34003047300,Census Tract 473,Bergen County,New Jersey,3138,250001,1033800,1472,2603,41,0,324,0,0,79,91,1.306565
2925,36061002100,Census Tract 21,New York County,New York,6488,250001,2000001,4168,4811,96,0,998,0,0,281,302,1.479655
359,34013020100,Census Tract 201,Essex County,New Jersey,4593,250001,1418300,2713,3653,16,0,721,0,0,100,103,0.348356
4594,36119009800,Census Tract 98,Westchester County,New York,4535,250001,1309100,2558,3514,29,0,593,8,0,124,267,0.639471

## Grouping your data results

In [19]:
census_data.groupby(['county'])['black_alone_percentage'].median()

county
 Bergen County          1.732085
 Bronx County          24.729952
 Dutchess County        4.776716
 Essex County          39.101947
 Hudson County          4.093098
 Hunterdon County       0.716893
 Kings County          10.103940
 Middlesex County       6.644010
 Monmouth County        2.867384
 Morris County          1.917672
 Nassau County          1.718599
 New York County        4.755496
 Ocean County           1.382887
 Orange County          7.473245
 Passaic County         5.485939
 Pike County            1.437285
 Putnam County          1.892110
 Queens County          3.382834
 Richmond County        3.937067
 Rockland County        5.567259
 Somerset County        3.270646
 Suffolk County         2.383189
 Sussex County          1.529354
 Union County          15.468311
 Westchester County     7.504983
Name: black_alone_percentage, dtype: float64

In [20]:
census_data.groupby(['state']).agg({'total_population': 'sum'})

               total_population
state
 New Jersey             6594915
 New York              13380318
 Pennsylvania             56210